#!/bin/bash
echo "Creating testbench"
PACKAGE=rcl_executor_testbench
BINARY=rcl_executor_testbench
GENERATOR_BIN=/home/jst3si/temp/ros2_ws/src/rcl_executor/rcl_executor_testbench/src/configure_test.py
RATE=1
MSG_SIZE=7
TOPOLOGY=A
PROCESS_TYPE=all
NUM_TOPICS=1
NUM_SUBS=3
NUM_PUBLISHED_MSG=3

echo args: $GENERATOR_BIN $PACKAGE $BINARY $RATE $NUM_PUBLISHED_MSG $MSG_SIZE $TOPOLOGY $PROCESS_TYPE $NUM_TOPICS $NUM_SUBS
python3 $GENERATOR_BIN $PACKAGE $BINARY $RATE $NUM_PUBLISHED_MSG $NUM_RECEIVED_MSG $MSG_SIZE $TOPOLOGY $PROCESS_TYPE $NUM_TOPICS $NUM_SUBS

